baseurl = "/"
languageCode = "en"
publishdir = "public"
canonifyUrls = true
enableEmoji = true
theme = "hugo-landing-page"
disableKinds = ["RSS","taxonomy","taxonomyTerm"] 
title = "progress-up - HTML5 multiple file uploader with progress display" 
[markup.goldmark.renderer]
    unsafe = true

[author]
    name = "Girish Venkatachalam"
    email = "girish@spamcheetah.com"
[params]
    description = "Progress-up - HTML5 multiple file uploader with progress display " 
    images = [] 
[[params.headermenu]]
   link = "/screenshots"
   title = "Screenshots"
[[params.headermenu]]
   link = "/docs"
   title = "Getting started"
[[params.headermenu]]
   link = "/demo"
   title = "Demo"
[[params.headermenu]]
   link = "/blog"
   title = "Blog"
#[[params.headermenu]]
#  link = "/pricing"
#  title = "Pricing"


[[params.social]]
    title = "Twitter"
    url = "https://twitter.com/girish1729" 
[[params.social]]
    title = "LinkedIn"
    url = "https://linkedin.com/in/girishvenkatachalam" 
