# SETUP
baseurl = "/"
DefaultContentLanguage = "en"
publishdir = "public"
canonifyUrls = "true"
theme = "hugo-landing-page"
disableKinds = ["RSS","taxonomy","taxonomyTerm"] 

title = "progress-up - HTML5 file upload progress plugin" 

[author]
    name = "Girish Venkatachalam"
    email = "girish@spamcheetah.com"

[params]
    description = "Progress-up - HTML5 multiple file upload plugin" 
    images = [] 
[[params.headermenu]]
   link = "/vue"
   title = "Vue"
[[params.headermenu]]
   link = "/angular"
   title = "Angular"
[[params.headermenu]]
   link = "/react"
   title = "React"
[[params.headermenu]]
   link = "/docs"
   title = "Docs"
[[params.headermenu]]
   link = "/demo"
   title = "Live demos"

[[params.social]]
    title = "Twitter"
    url = "https://twitter.com/girish1729" 
[[params.social]]
    title = "LinkedIn"
    url = "https://linkedin.com/in/girishvenkatachalam" 
